-- Generated by Fintor Jozsef's script.

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity tb_CPU_top is
end tb_CPU_top;

architecture tb of tb_CPU_top is
	component CPU_top
		port (
			sys_clock	:	in STD_LOGIC;
			alu_out_reg	:	inout STD_LOGIC_VECTOR (7 downto 0));
	end component;

	 signal sys_clock	: STD_LOGIC;
	 signal alu_out_reg	: STD_LOGIC_VECTOR (7 downto 0);

begin

	dut : CPU_top
	port map (
			sys_clock	 => sys_clock,
			alu_out_reg	 => alu_out_reg);

	stimuli : process

	begin
		-- Write initialization here.
        sys_clock <= '0';
        wait for 20ns;
        
		-- Write stimuli here.
        for i in 0 to 10000 loop
            sys_clock <= ( sys_clock xor '1');
            wait for 20ns;
        end loop;

		wait;
	end process;

end tb;