-- Generated by Fintor Jozsef's script.

library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;

entity tb_reg_file_wrapper is
end tb_reg_file_wrapper;

architecture tb of tb_reg_file_wrapper is
	component reg_file_wrapper
		port (
			BRAM_PORTA_0_addr	:	in STD_LOGIC_VECTOR ( 3 downto 0 );
			BRAM_PORTA_0_clk	:	in STD_LOGIC;
			BRAM_PORTA_0_din	:	in STD_LOGIC_VECTOR ( 7 downto 0 );
			BRAM_PORTA_0_dout	:	out STD_LOGIC_VECTOR ( 7 downto 0 );
			BRAM_PORTA_0_en	:	in STD_LOGIC;
			BRAM_PORTA_0_rst	:	in STD_LOGIC;
			BRAM_PORTA_0_we	:	in STD_LOGIC_VECTOR ( 0 to 0 ));
	end component;

	 signal BRAM_PORTA_0_addr	: STD_LOGIC_VECTOR ( 3 downto 0 );
	 signal BRAM_PORTA_0_clk	: STD_LOGIC;
	 signal BRAM_PORTA_0_din	: STD_LOGIC_VECTOR ( 7 downto 0 );
	 signal BRAM_PORTA_0_dout	: STD_LOGIC_VECTOR ( 7 downto 0 );
	 signal BRAM_PORTA_0_en	: STD_LOGIC;
	 signal BRAM_PORTA_0_rst	: STD_LOGIC;
	 signal BRAM_PORTA_0_we	: STD_LOGIC_VECTOR ( 0 to 0 );

begin

	dut : reg_file_wrapper
	port map (
			BRAM_PORTA_0_addr	 => BRAM_PORTA_0_addr,
			BRAM_PORTA_0_clk	 => BRAM_PORTA_0_clk,
			BRAM_PORTA_0_din	 => BRAM_PORTA_0_din,
			BRAM_PORTA_0_dout	 => BRAM_PORTA_0_dout,
			BRAM_PORTA_0_en	 => BRAM_PORTA_0_en,
			BRAM_PORTA_0_rst	 => BRAM_PORTA_0_rst,
			BRAM_PORTA_0_we	 => BRAM_PORTA_0_we);

	stimuli : process

	begin
		-- Write initialization here.


		-- Write stimuli here.


		wait;
	end process;

end tb;