## Generated by Fintor Jozsef's script.

## Clock signal
#set_property PACKAGE_PIN E3 [get_ports {mclk}]
	#set_property IOSTANDARD LVCMOS33 [get_ports {mclk}]
	# create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {mclk}];

set_property PACKAGE_PIN J15 [get_ports {sys_clock}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {sys_clock}]

set_property PACKAGE_PIN L16 [get_ports {pc_ce}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {pc_ce}]

set_property PACKAGE_PIN H17 [get_ports {alu_out_reg[0]}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {alu_out_reg[0]}]

set_property PACKAGE_PIN K15 [get_ports {alu_out_reg[1]}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {alu_out_reg[1]}]

set_property PACKAGE_PIN J13 [get_ports {alu_out_reg[2]}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {alu_out_reg[2]}]

set_property PACKAGE_PIN N14 [get_ports {alu_out_reg[3]}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {alu_out_reg[3]}]

set_property PACKAGE_PIN R18 [get_ports {alu_out_reg[4]}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {alu_out_reg[4]}]

set_property PACKAGE_PIN V17 [get_ports {alu_out_reg[5]}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {alu_out_reg[5]}]

set_property PACKAGE_PIN U17 [get_ports {alu_out_reg[6]}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {alu_out_reg[6]}]

set_property PACKAGE_PIN U16 [get_ports {alu_out_reg[7]}]
	 set_property IOSTANDARD LVCMOS33 [get_ports {alu_out_reg[7]}]

