# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/nexys_con.xdc

# Block Designs: bd/pc/pc.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pc || ORIG_REF_NAME==pc} -quiet] -quiet

# IP: bd/pc/ip/pc_c_counter_binary_0_0/pc_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pc_c_counter_binary_0_0 || ORIG_REF_NAME==pc_c_counter_binary_0_0} -quiet] -quiet

# Block Designs: bd/reg_file/reg_file.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==reg_file || ORIG_REF_NAME==reg_file} -quiet] -quiet

# IP: bd/reg_file/ip/reg_file_blk_mem_gen_0_0/reg_file_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==reg_file_blk_mem_gen_0_0 || ORIG_REF_NAME==reg_file_blk_mem_gen_0_0} -quiet] -quiet

# XDC: bd/pc/pc_ooc.xdc

# XDC: bd/reg_file/reg_file_ooc.xdc
